version: "3"

services:
  app:
    image: our-covid-voices/frontend/app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT:-3000}:80"
    command: pm2-dev start yarn -- run dev:server
    restart: on-failure
